# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/verilog/breakout_final/breakout/break_1.srcs/sources_1/ip/CustomClock/CustomClock.xci
# IP: The module: 'CustomClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/verilog/breakout_final/breakout/break_1.srcs/sources_1/ip/CustomClock/CustomClock.xci
# IP: The module: 'CustomClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/verilog/breakout_final/breakout/break_1.gen/sources_1/ip/CustomClock/CustomClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CustomClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
