set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN AA6 [get_ports {LED[1]}]
set_property PACKAGE_PIN V7 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_B]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_G]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_R]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports VGA_HS]
set_property PACKAGE_PIN R16 [get_ports VGA_VS]
set_property PACKAGE_PIN AB22 [get_ports VGA_B]
set_property PACKAGE_PIN AA21 [get_ports VGA_G]
set_property PACKAGE_PIN T20 [get_ports VGA_R]

set_property IOSTANDARD LVCMOS33 [get_ports button_L]
set_property IOSTANDARD LVCMOS33 [get_ports button_R]
set_property PACKAGE_PIN T1 [get_ports button_L]

set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_sda]

set_property PACKAGE_PIN Y13 [get_ports ddc_scl]
set_property PACKAGE_PIN AA14 [get_ports ddc_sda]



set_property PACKAGE_PIN T3 [get_ports button_R]

set_property IOSTANDARD LVCMOS33 [get_ports stop]
set_property PACKAGE_PIN N15 [get_ports stop]

set_property PACKAGE_PIN P19 [get_ports restart]
set_property IOSTANDARD LVCMOS33 [get_ports restart]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_p]
set_property PACKAGE_PIN W11 [get_ports tmds_clk_p]
set_property PACKAGE_PIN W12 [get_ports tmds_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n[0]}]
set_property PACKAGE_PIN V10 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN W10 [get_ports {tmds_data_n[2]}]
set_property PACKAGE_PIN AA10 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN AA11 [get_ports {tmds_data_n[1]}]
set_property PACKAGE_PIN AA9 [get_ports {tmds_data_p[0]}]
set_property PACKAGE_PIN AB10 [get_ports {tmds_data_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN AB18 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN U17 [get_ports {seg_led[1]}]
set_property PACKAGE_PIN U18 [get_ports {seg_led[2]}]
set_property PACKAGE_PIN P14 [get_ports {seg_led[3]}]
set_property PACKAGE_PIN R14 [get_ports {seg_led[4]}]
set_property PACKAGE_PIN R18 [get_ports {seg_led[5]}]
set_property PACKAGE_PIN T18 [get_ports {seg_led[6]}]
set_property PACKAGE_PIN N17 [get_ports {seg_led[7]}]
set_property PACKAGE_PIN AA18 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN W17 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN V17 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN AB20 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN AA19 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN V19 [get_ports {seg_sel[5]}]
set_property PACKAGE_PIN V18 [get_ports {seg_sel[6]}]
set_property PACKAGE_PIN Y19 [get_ports {seg_sel[7]}]



set_property IOSTANDARD LVCMOS33 [get_ports attack]
set_property PACKAGE_PIN R19 [get_ports attack]

set_property IOSTANDARD LVCMOS33 [get_ports unfail]
set_property PACKAGE_PIN R17 [get_ports unfail]

set_property IOSTANDARD LVCMOS33 [get_ports Paddlespeed]
set_property IOSTANDARD LVCMOS33 [get_ports speed]
set_property PACKAGE_PIN P16 [get_ports speed]
set_property PACKAGE_PIN N14 [get_ports Paddlespeed]


set_property IOSTANDARD LVCMOS33 [get_ports beep]
set_property PACKAGE_PIN P20 [get_ports beep]

set_property IOSTANDARD LVCMOS33 [get_ports score]
set_property PACKAGE_PIN R19 [get_ports score]
